package com.caucraft.mciguiv3.pmgr;

import java.awt.event.KeyEvent;
import java.util.Arrays;

/**
 *
 * @author caucow
 */
public class PasswordDialogPanel extends javax.swing.JPanel {

    /**
     * Creates new form PasswordDialog
     */
    public PasswordDialogPanel(PasswordDialog pDialog, boolean canDecrypt) {
        initComponents();
        passDialog = pDialog;
        decryptButton.setVisible(canDecrypt);
    }
    
    public void setCanDecrypt(boolean canDecrypt) {
        decryptButton.setVisible(canDecrypt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passFieldLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        showPassCheckbox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();

        passFieldLabel.setText("Password:");
        passFieldLabel.setFocusable(false);

        passField.setEchoChar('\u2022');
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordDialogPanel.this.keyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordDialogPanel.this.keyTyped(evt);
            }
        });

        showPassCheckbox.setText("Show Password");
        showPassCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCheckboxActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPressed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPressed(evt);
            }
        });

        decryptButton.setText("Decrypt Accounts File");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passFieldLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decryptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showPassCheckbox)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passFieldLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showPassCheckbox)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(decryptButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private PasswordDialog passDialog;
    private Result result = Result.NONE;
    
    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        switch (evt.getID()) {
            case KeyEvent.VK_ESCAPE:
                cancelPressed(null);
                break;
            case KeyEvent.VK_ENTER:
                okPressed(null);
                break;
        }
    }//GEN-LAST:event_keyPressed

    private void okPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPressed
        char[] pass = passField.getPassword();
        if (pass.length == 0) {
            Arrays.fill(pass, '\u0000');
            return;
        }
        result = Result.ACCEPT;
        passDialog.setVisible(false);
    }//GEN-LAST:event_okPressed

    private void cancelPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPressed
        result = Result.CANCEL;
        passDialog.setVisible(false);
    }//GEN-LAST:event_cancelPressed

    private void showPassCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCheckboxActionPerformed
        passField.setEchoChar(showPassCheckbox.isSelected() ? '\u0000' : '\u2022');
    }//GEN-LAST:event_showPassCheckboxActionPerformed

    private void keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTyped
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                okButton.doClick();
                break;
            case KeyEvent.VK_ESCAPE:
                cancelButton.doClick();
                break;
        }
    }//GEN-LAST:event_keyTyped

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        result = Result.DECRYPT;
        passDialog.setVisible(false);
    }//GEN-LAST:event_decryptButtonActionPerformed
    
    public char[] getPassword() {
        if (result == Result.ACCEPT || result == Result.DECRYPT) {
            return passField.getPassword();
        }
        return null;
    }
    
    public Result getResult() {
        return result;
    }
    
    public enum Result {
        ACCEPT(),
        DECRYPT(),
        CANCEL(),
        NONE();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton decryptButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passFieldLabel;
    private javax.swing.JCheckBox showPassCheckbox;
    // End of variables declaration//GEN-END:variables
}
